# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5

# RUN: llc -mtriple=riscv32 -mattr=+zfa,+zfh -run-pass=legalizer -o - %s\
# RUN: | FileCheck %s --check-prefixes=CHECK-ZFA-f16
# RUN: llc -mtriple=riscv64 -mattr=+zfa,+zfh -run-pass=legalizer -o - %s\
# RUN: | FileCheck %s --check-prefixes=CHECK-ZFA-f16

---
name:            FCEIL
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $f10_h

    ; CHECK-ZFA-f16-LABEL: name: FCEIL
    ; CHECK-ZFA-f16: liveins: $f10_h
    ; CHECK-ZFA-f16-NEXT: {{  $}}
    ; CHECK-ZFA-f16-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-ZFA-f16-NEXT: [[FCEIL:%[0-9]+]]:_(s16) = G_FCEIL [[COPY]]
    ; CHECK-ZFA-f16-NEXT: $f10_h = COPY [[FCEIL]](s16)
    ; CHECK-ZFA-f16-NEXT: PseudoRET implicit $f10_h
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = G_FCEIL %0
    $f10_h =  COPY %1
    PseudoRET implicit $f10_h

...
---
name:            FFLOOR
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $f10_h

    ; CHECK-ZFA-f16-LABEL: name: FFLOOR
    ; CHECK-ZFA-f16: liveins: $f10_h
    ; CHECK-ZFA-f16-NEXT: {{  $}}
    ; CHECK-ZFA-f16-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-ZFA-f16-NEXT: [[FFLOOR:%[0-9]+]]:_(s16) = G_FFLOOR [[COPY]]
    ; CHECK-ZFA-f16-NEXT: $f10_h = COPY [[FFLOOR]](s16)
    ; CHECK-ZFA-f16-NEXT: PseudoRET implicit $f10_h
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = G_FFLOOR %0
    $f10_h = COPY %1
    PseudoRET implicit $f10_h

...
---
name:            FRINT
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $f10_h

    ; CHECK-ZFA-f16-LABEL: name: FRINT
    ; CHECK-ZFA-f16: liveins: $f10_h
    ; CHECK-ZFA-f16-NEXT: {{  $}}
    ; CHECK-ZFA-f16-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-ZFA-f16-NEXT: [[FRINT:%[0-9]+]]:_(s16) = G_FRINT [[COPY]]
    ; CHECK-ZFA-f16-NEXT: $f10_h = COPY [[FRINT]](s16)
    ; CHECK-ZFA-f16-NEXT: PseudoRET implicit $f10_h
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = G_FRINT %0
    $f10_h =  COPY %1
    PseudoRET implicit $f10_h

...
---
name:            FNEARBYINT
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $f10_h

    ; CHECK-ZFA-f16-LABEL: name: FNEARBYINT
    ; CHECK-ZFA-f16: liveins: $f10_h
    ; CHECK-ZFA-f16-NEXT: {{  $}}
    ; CHECK-ZFA-f16-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-ZFA-f16-NEXT: [[FNEARBYINT:%[0-9]+]]:_(s16) = G_FNEARBYINT [[COPY]]
    ; CHECK-ZFA-f16-NEXT: $f10_h = COPY [[FNEARBYINT]](s16)
    ; CHECK-ZFA-f16-NEXT: PseudoRET implicit $f10_h
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = G_FNEARBYINT %0
    $f10_h =  COPY %1
    PseudoRET implicit $f10_h

...
---
name:            INTRINSIC_TRUNC
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $f10_h

    ; CHECK-ZFA-f16-LABEL: name: INTRINSIC_TRUNC
    ; CHECK-ZFA-f16: liveins: $f10_h
    ; CHECK-ZFA-f16-NEXT: {{  $}}
    ; CHECK-ZFA-f16-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-ZFA-f16-NEXT: [[INTRINSIC_TRUNC:%[0-9]+]]:_(s16) = G_INTRINSIC_TRUNC [[COPY]]
    ; CHECK-ZFA-f16-NEXT: $f10_h = COPY [[INTRINSIC_TRUNC]](s16)
    ; CHECK-ZFA-f16-NEXT: PseudoRET implicit $f10_h
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = G_INTRINSIC_TRUNC %0
    $f10_h =  COPY %1
    PseudoRET implicit $f10_h

...
---
name:            INTRINSIC_ROUND
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $f10_h

    ; CHECK-ZFA-f16-LABEL: name: INTRINSIC_ROUND
    ; CHECK-ZFA-f16: liveins: $f10_h
    ; CHECK-ZFA-f16-NEXT: {{  $}}
    ; CHECK-ZFA-f16-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-ZFA-f16-NEXT: [[INTRINSIC_ROUND:%[0-9]+]]:_(s16) = G_INTRINSIC_ROUND [[COPY]]
    ; CHECK-ZFA-f16-NEXT: $f10_h = COPY [[INTRINSIC_ROUND]](s16)
    ; CHECK-ZFA-f16-NEXT: PseudoRET implicit $f10_h
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = G_INTRINSIC_ROUND %0
    $f10_h =  COPY %1
    PseudoRET implicit $f10_h

...
---
name:            INTRINSIC_ROUNDEVEN
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $f10_h

    ; CHECK-ZFA-f16-LABEL: name: INTRINSIC_ROUNDEVEN
    ; CHECK-ZFA-f16: liveins: $f10_h
    ; CHECK-ZFA-f16-NEXT: {{  $}}
    ; CHECK-ZFA-f16-NEXT: [[COPY:%[0-9]+]]:_(s16) = COPY $f10_h
    ; CHECK-ZFA-f16-NEXT: [[INTRINSIC_ROUNDEVEN:%[0-9]+]]:_(s16) = G_INTRINSIC_ROUNDEVEN [[COPY]]
    ; CHECK-ZFA-f16-NEXT: $f10_h = COPY [[INTRINSIC_ROUNDEVEN]](s16)
    ; CHECK-ZFA-f16-NEXT: PseudoRET implicit $f10_h
    %0:_(s16) = COPY $f10_h
    %1:_(s16) = G_INTRINSIC_ROUNDEVEN %0
    $f10_h = COPY %1
    PseudoRET implicit $f10_h

...
